#SPDX-License-Identifier: MIT-0
---
# tasks file for install_git
- name: Update the package index on the VM
  apt:
    update_cache: yes

- name: Install Git
  apt:
    name:
      - git
    state: present
