#SPDX-License-Identifier: MIT-0
---
# tasks file for backend_deployment
- name: Create .env file in the cloned repo directory
  ansible.builtin.file:
    path: /home/vagrant/yolo/backend/.env
    state: touch
    mode: "0644"
    owner: vagrant
    group: vagrant
  become: yes

- name: Add an entry to the .env file
  ansible.builtin.lineinfile:
    path: /home/vagrant/yolo/backend/.env
    line: "MONGODB_URI=mongodb+srv://douglaswangome:m7BNXS976KGvskKn@yolomy.m1ms1dd.mongodb.net/?retryWrites=true&w=majority&appName=yolomy"
    # Create the file if it doesn't exist
    create: yes
    owner: vagrant
    group: vagrant
    mode: "0644"
  become: yes
  become_user: vagrant

- name: Build backend Docker image from Dockerfile
  community.docker.docker_image:
    name: yolo_backend
    build:
      path: /home/vagrant/yolo/backend/
      pull: yes
    source: build
    state: present
  become: yes
  become_user: vagrant

- name: Run Docker container from the built image
  community.docker.docker_container:
    name: yolo_backend_container
    image: yolo_backend
    state: started
    recreate: yes
    networks:
      - name: yolo_network
    ports:
      - "5000:5000"
    env_file: /home/vagrant/yolo/backend/.env
  become: yes
  become_user: vagrant
