#SPDX-License-Identifier: MIT-0
---
# tasks file for frontend_deployment
- name: Build frontend Docker image from Dockerfile
  community.docker.docker_image:
    name: yolo_frontend
    build:
      path: /home/vagrant/yolo/client/
      pull: yes
    source: build
    state: present
  become: yes
  become_user: vagrant

- name: Run Docker container from the built image
  community.docker.docker_container:
    name: yolo_frontend_container
    image: yolo_frontend
    state: started
    recreate: yes
    networks:
      - name: yolo_network
    ports:
      - "3000:3000"
  become: yes
  become_user: vagrant
