#SPDX-License-Identifier: MIT-0
---
# tasks file for install_docker
- name: Update the package index on the VM
  apt:
    update_cache: yes

- name: Install pre-requisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add the GPG Key for the official Docker repo
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  # Prevents the task form running unnecessarily on subsequent provisions
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg
  become: yes

- name: Add Docker repo to APT sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker
    update_cache: yes
  become: yes

- name: Finally download Docker on the VM
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure that Docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add 'vagrant' user to the 'docker' group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    # This ensures the user is added to 'docker' without removing other groups
    append: yes
  become: yes

- name: Install python3-pip (required for docker Python SDK)
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Python SDK
  ansible.builtin.pip:
    name: docker
    state: present
    executable: pip3 # Ensure pip3 is used
  become: yes
