---
galaxy_info:
  author: Douglas Wangome
  description: Ansible role for deploying the frontend application
  company: Moringa School
  license: license
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
  galaxy_tags:
    - web
    - frontend
    - docker
    - react
dependencies: []
